# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tadeusz/Desktop/ntru

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tadeusz/Desktop/ntru

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tadeusz/Desktop/ntru/CMakeFiles /home/tadeusz/Desktop/ntru/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tadeusz/Desktop/ntru/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ntrulib

# Build rule for target.
ntrulib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntrulib
.PHONY : ntrulib

# fast build rule for target.
ntrulib/fast:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/build
.PHONY : ntrulib/fast

#=============================================================================
# Target rules for targets named polynomial_test

# Build rule for target.
polynomial_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 polynomial_test
.PHONY : polynomial_test

# fast build rule for target.
polynomial_test/fast:
	$(MAKE) -f tests/CMakeFiles/polynomial_test.dir/build.make tests/CMakeFiles/polynomial_test.dir/build
.PHONY : polynomial_test/fast

#=============================================================================
# Target rules for targets named ntru_test

# Build rule for target.
ntru_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntru_test
.PHONY : ntru_test

# fast build rule for target.
ntru_test/fast:
	$(MAKE) -f tests/CMakeFiles/ntru_test.dir/build.make tests/CMakeFiles/ntru_test.dir/build
.PHONY : ntru_test/fast

#=============================================================================
# Target rules for targets named rationals_test

# Build rule for target.
rationals_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rationals_test
.PHONY : rationals_test

# fast build rule for target.
rationals_test/fast:
	$(MAKE) -f tests/CMakeFiles/rationals_test.dir/build.make tests/CMakeFiles/rationals_test.dir/build
.PHONY : rationals_test/fast

src/debug.o: src/debug.c.o

.PHONY : src/debug.o

# target to build an object file
src/debug.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/debug.c.o
.PHONY : src/debug.c.o

src/debug.i: src/debug.c.i

.PHONY : src/debug.i

# target to preprocess a source file
src/debug.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/debug.c.i
.PHONY : src/debug.c.i

src/debug.s: src/debug.c.s

.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/debug.c.s
.PHONY : src/debug.c.s

src/hashtable.o: src/hashtable.c.o

.PHONY : src/hashtable.o

# target to build an object file
src/hashtable.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/hashtable.c.o
.PHONY : src/hashtable.c.o

src/hashtable.i: src/hashtable.c.i

.PHONY : src/hashtable.i

# target to preprocess a source file
src/hashtable.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/hashtable.c.i
.PHONY : src/hashtable.c.i

src/hashtable.s: src/hashtable.c.s

.PHONY : src/hashtable.s

# target to generate assembly for a file
src/hashtable.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/hashtable.c.s
.PHONY : src/hashtable.c.s

src/integer_arithmetic.o: src/integer_arithmetic.c.o

.PHONY : src/integer_arithmetic.o

# target to build an object file
src/integer_arithmetic.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/integer_arithmetic.c.o
.PHONY : src/integer_arithmetic.c.o

src/integer_arithmetic.i: src/integer_arithmetic.c.i

.PHONY : src/integer_arithmetic.i

# target to preprocess a source file
src/integer_arithmetic.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/integer_arithmetic.c.i
.PHONY : src/integer_arithmetic.c.i

src/integer_arithmetic.s: src/integer_arithmetic.c.s

.PHONY : src/integer_arithmetic.s

# target to generate assembly for a file
src/integer_arithmetic.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/integer_arithmetic.c.s
.PHONY : src/integer_arithmetic.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory.o: src/memory.c.o

.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/memory.c.s
.PHONY : src/memory.c.s

src/ntru.o: src/ntru.c.o

.PHONY : src/ntru.o

# target to build an object file
src/ntru.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/ntru.c.o
.PHONY : src/ntru.c.o

src/ntru.i: src/ntru.c.i

.PHONY : src/ntru.i

# target to preprocess a source file
src/ntru.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/ntru.c.i
.PHONY : src/ntru.c.i

src/ntru.s: src/ntru.c.s

.PHONY : src/ntru.s

# target to generate assembly for a file
src/ntru.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/ntru.c.s
.PHONY : src/ntru.c.s

src/polynomial.o: src/polynomial.c.o

.PHONY : src/polynomial.o

# target to build an object file
src/polynomial.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/polynomial.c.o
.PHONY : src/polynomial.c.o

src/polynomial.i: src/polynomial.c.i

.PHONY : src/polynomial.i

# target to preprocess a source file
src/polynomial.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/polynomial.c.i
.PHONY : src/polynomial.c.i

src/polynomial.s: src/polynomial.c.s

.PHONY : src/polynomial.s

# target to generate assembly for a file
src/polynomial.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/polynomial.c.s
.PHONY : src/polynomial.c.s

src/quotient_polynomial_ring.o: src/quotient_polynomial_ring.c.o

.PHONY : src/quotient_polynomial_ring.o

# target to build an object file
src/quotient_polynomial_ring.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/quotient_polynomial_ring.c.o
.PHONY : src/quotient_polynomial_ring.c.o

src/quotient_polynomial_ring.i: src/quotient_polynomial_ring.c.i

.PHONY : src/quotient_polynomial_ring.i

# target to preprocess a source file
src/quotient_polynomial_ring.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/quotient_polynomial_ring.c.i
.PHONY : src/quotient_polynomial_ring.c.i

src/quotient_polynomial_ring.s: src/quotient_polynomial_ring.c.s

.PHONY : src/quotient_polynomial_ring.s

# target to generate assembly for a file
src/quotient_polynomial_ring.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/quotient_polynomial_ring.c.s
.PHONY : src/quotient_polynomial_ring.c.s

src/rationals.o: src/rationals.c.o

.PHONY : src/rationals.o

# target to build an object file
src/rationals.c.o:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/rationals.c.o
.PHONY : src/rationals.c.o

src/rationals.i: src/rationals.c.i

.PHONY : src/rationals.i

# target to preprocess a source file
src/rationals.c.i:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/rationals.c.i
.PHONY : src/rationals.c.i

src/rationals.s: src/rationals.c.s

.PHONY : src/rationals.s

# target to generate assembly for a file
src/rationals.c.s:
	$(MAKE) -f CMakeFiles/ntrulib.dir/build.make CMakeFiles/ntrulib.dir/src/rationals.c.s
.PHONY : src/rationals.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ntrulib"
	@echo "... edit_cache"
	@echo "... polynomial_test"
	@echo "... ntru_test"
	@echo "... rationals_test"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/hashtable.o"
	@echo "... src/hashtable.i"
	@echo "... src/hashtable.s"
	@echo "... src/integer_arithmetic.o"
	@echo "... src/integer_arithmetic.i"
	@echo "... src/integer_arithmetic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/ntru.o"
	@echo "... src/ntru.i"
	@echo "... src/ntru.s"
	@echo "... src/polynomial.o"
	@echo "... src/polynomial.i"
	@echo "... src/polynomial.s"
	@echo "... src/quotient_polynomial_ring.o"
	@echo "... src/quotient_polynomial_ring.i"
	@echo "... src/quotient_polynomial_ring.s"
	@echo "... src/rationals.o"
	@echo "... src/rationals.i"
	@echo "... src/rationals.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

